name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/nightly/sdk:10.0-preview-alpine

    steps:
      - uses: actions/checkout@v4
            
      - name: Run tests
        run: |
          dotnet test
        working-directory: .
